# Generated by Django 3.0.4 on 2020-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Code', models.CharField(max_length=20)),
                ('Value', models.CharField(max_length=20)),
                ('Currency', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'curnt',
            },
        ),
    ]
