# Generated by Django 3.0.4 on 2020-03-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200329_1933'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pp',
            table='home_xcurnt',
        ),
    ]
