# Generated by Django 3.0.4 on 2020-03-29 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200329_1947'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pp',
            table='home_now',
        ),
    ]
