# Generated by Django 3.0.4 on 2020-03-29 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200329_2010'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pp',
            table='home_xyz',
        ),
    ]
