# Generated by Django 3.0.4 on 2020-03-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200329_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pp',
            old_name='Name',
            new_name='xme',
        ),
    ]
