# Generated by Django 3.0.4 on 2020-03-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200329_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pp',
            old_name='xme',
            new_name='Name',
        ),
    ]
